"""Expand every team in ``data/teams_2026.json`` to a full 26-man call-up.

The base file ships a recognisable *starting* core per nation (with full FM
attributes). This script appends the rest of each squad as lighter entries
(name / pos / rating / club / age, no attributes) — exactly the pattern used
for Portugal's bench. ``worldcup.fm_rating`` falls back to ``rating`` when a
player has no attributes, so these depth players work everywhere immediately,
and the deeper benches make the live engine's substitutions fire for everyone.

Ratings/clubs/ages are curated estimates (see the file's ``_about`` note),
consistent with the existing data. Re-running is idempotent: a player already
present (by name) is skipped, so each team converges on 26.

Run:  py -3.13 scripts/add_full_squads.py
"""

from __future__ import annotations

import json
from pathlib import Path

DATA = Path(__file__).resolve().parents[1] / "data" / "teams_2026.json"

# team -> list of (name, pos, rating, club, age) appended to reach 26.
ADDITIONS: dict[str, list[tuple[str, str, int, str, int]]] = {
    "Argentina": [
        ("Geronimo Rulli", "GK", 80, "Marseille", 33),
        ("Walter Benitez", "GK", 78, "Crystal Palace", 33),
        ("Nicolas Tagliafico", "DEF", 80, "Lyon", 33),
        ("Lisandro Martinez", "DEF", 83, "Manchester United", 28),
        ("Gonzalo Montiel", "DEF", 78, "River Plate", 29),
        ("Marcos Acuna", "DEF", 78, "River Plate", 34),
        ("Leonardo Balerdi", "DEF", 79, "Marseille", 27),
        ("Leandro Paredes", "MID", 81, "Boca Juniors", 31),
        ("Giovani Lo Celso", "MID", 81, "Real Betis", 30),
        ("Exequiel Palacios", "MID", 81, "Bayer Leverkusen", 27),
        ("Thiago Almada", "MID", 81, "Atletico Madrid", 25),
        ("Maximo Perrone", "MID", 76, "Como", 23),
        ("Nico Gonzalez", "FWD", 81, "Juventus", 28),
        ("Giuliano Simeone", "FWD", 79, "Atletico Madrid", 23),
        ("Alejandro Garnacho", "FWD", 81, "Chelsea", 21),
        ("Valentin Castellanos", "FWD", 78, "Lazio", 27),
    ],
    "Spain": [
        ("David Raya", "GK", 85, "Arsenal", 30),
        ("Robert Sanchez", "GK", 80, "Chelsea", 28),
        ("Aymeric Laporte", "DEF", 82, "Athletic Bilbao", 31),
        ("Pau Cubarsi", "DEF", 83, "Barcelona", 19),
        ("Dani Vivian", "DEF", 80, "Athletic Bilbao", 26),
        ("Alejandro Grimaldo", "DEF", 83, "Bayer Leverkusen", 30),
        ("Pedro Porro", "DEF", 81, "Tottenham", 26),
        ("Martin Zubimendi", "MID", 85, "Arsenal", 27),
        ("Mikel Merino", "MID", 83, "Arsenal", 30),
        ("Dani Olmo", "MID", 85, "Barcelona", 27),
        ("Fermin Lopez", "MID", 82, "Barcelona", 22),
        ("Alex Baena", "MID", 81, "Atletico Madrid", 24),
        ("Mikel Oyarzabal", "FWD", 84, "Real Sociedad", 28),
        ("Ferran Torres", "FWD", 83, "Barcelona", 25),
        ("Ayoze Perez", "FWD", 79, "Villarreal", 32),
        ("Samu Aghehowa", "FWD", 80, "Porto", 21),
    ],
    "France": [
        ("Brice Samba", "GK", 81, "Rennes", 31),
        ("Lucas Chevalier", "GK", 81, "PSG", 24),
        ("Ibrahima Konate", "DEF", 85, "Liverpool", 26),
        ("Lucas Hernandez", "DEF", 82, "PSG", 30),
        ("Benjamin Pavard", "DEF", 82, "Inter Milan", 30),
        ("Wesley Fofana", "DEF", 81, "Chelsea", 25),
        ("N'Golo Kante", "MID", 84, "Al-Ittihad", 34),
        ("Adrien Rabiot", "MID", 84, "AC Milan", 31),
        ("Warren Zaire-Emery", "MID", 82, "PSG", 20),
        ("Manu Kone", "MID", 82, "AS Roma", 24),
        ("Khephren Thuram", "MID", 82, "Juventus", 25),
        ("Michael Olise", "FWD", 86, "Bayern Munich", 24),
        ("Bradley Barcola", "FWD", 84, "PSG", 23),
        ("Randal Kolo Muani", "FWD", 82, "Juventus", 27),
        ("Hugo Ekitike", "FWD", 83, "Liverpool", 23),
    ],
    "England": [
        ("Dean Henderson", "GK", 81, "Crystal Palace", 29),
        ("Nick Pope", "GK", 80, "Newcastle", 34),
        ("Ezri Konsa", "DEF", 81, "Aston Villa", 28),
        ("Levi Colwill", "DEF", 82, "Chelsea", 23),
        ("Trent Alexander-Arnold", "DEF", 84, "Real Madrid", 27),
        ("Reece James", "DEF", 83, "Chelsea", 26),
        ("Tino Livramento", "DEF", 80, "Newcastle", 23),
        ("Conor Gallagher", "MID", 82, "Atletico Madrid", 26),
        ("Adam Wharton", "MID", 81, "Crystal Palace", 22),
        ("Curtis Jones", "MID", 81, "Liverpool", 25),
        ("Morgan Rogers", "MID", 82, "Aston Villa", 23),
        ("Elliot Anderson", "MID", 80, "Nottingham Forest", 23),
        ("Anthony Gordon", "FWD", 83, "Newcastle", 25),
        ("Marcus Rashford", "FWD", 84, "Barcelona", 28),
        ("Ollie Watkins", "FWD", 83, "Aston Villa", 30),
        ("Eberechi Eze", "FWD", 83, "Arsenal", 27),
    ],
    "Brazil": [
        ("Bento", "GK", 81, "Al-Nassr", 26),
        ("Ederson", "GK", 84, "Fenerbahce", 32),
        ("Eder Militao", "DEF", 84, "Real Madrid", 28),
        ("Lucas Beraldo", "DEF", 79, "PSG", 22),
        ("Wesley", "DEF", 80, "AS Roma", 22),
        ("Vanderson", "DEF", 80, "Monaco", 24),
        ("Murillo", "DEF", 81, "Nottingham Forest", 23),
        ("Andre", "MID", 81, "Wolves", 24),
        ("Joelinton", "MID", 82, "Newcastle", 29),
        ("Gerson", "MID", 81, "Zenit", 28),
        ("Andreas Pereira", "MID", 79, "Palmeiras", 30),
        ("Estevao", "FWD", 83, "Chelsea", 18),
        ("Savinho", "FWD", 83, "Manchester City", 21),
        ("Matheus Cunha", "FWD", 83, "Manchester United", 26),
        ("Igor Jesus", "FWD", 78, "Nottingham Forest", 24),
    ],
    "Netherlands": [
        ("Mark Flekken", "GK", 80, "Bayer Leverkusen", 32),
        ("Nick Olij", "GK", 77, "Feyenoord", 30),
        ("Stefan de Vrij", "DEF", 81, "Inter Milan", 34),
        ("Lutsharel Geertruida", "DEF", 80, "RB Leipzig", 25),
        ("Jurrien Timber", "DEF", 84, "Arsenal", 24),
        ("Micky van de Ven", "DEF", 83, "Tottenham", 25),
        ("Jan Paul van Hecke", "DEF", 80, "Brighton", 25),
        ("Ryan Gravenberch", "MID", 85, "Liverpool", 23),
        ("Mats Wieffer", "MID", 80, "Brighton", 26),
        ("Joey Veerman", "MID", 80, "PSV", 27),
        ("Quinten Timber", "MID", 81, "Feyenoord", 24),
        ("Jerdy Schouten", "MID", 80, "PSV", 29),
        ("Donyell Malen", "FWD", 81, "Aston Villa", 27),
        ("Brian Brobbey", "FWD", 80, "Ajax", 24),
        ("Wout Weghorst", "FWD", 79, "Ajax", 33),
        ("Noa Lang", "FWD", 80, "Napoli", 26),
        ("Justin Kluivert", "FWD", 80, "Bournemouth", 26),
    ],
    "Germany": [
        ("Oliver Baumann", "GK", 80, "Hoffenheim", 35),
        ("Alexander Nubel", "GK", 81, "Stuttgart", 29),
        ("Nico Schlotterbeck", "DEF", 83, "Borussia Dortmund", 26),
        ("Waldemar Anton", "DEF", 80, "Borussia Dortmund", 29),
        ("Robin Koch", "DEF", 80, "Eintracht Frankfurt", 29),
        ("David Raum", "DEF", 81, "RB Leipzig", 28),
        ("Maximilian Mittelstadt", "DEF", 80, "Stuttgart", 29),
        ("Ridle Baku", "DEF", 78, "RB Leipzig", 28),
        ("Leon Goretzka", "MID", 83, "Bayern Munich", 31),
        ("Pascal Gross", "MID", 81, "Borussia Dortmund", 34),
        ("Robert Andrich", "MID", 81, "Bayer Leverkusen", 31),
        ("Angelo Stiller", "MID", 82, "Stuttgart", 24),
        ("Felix Nmecha", "MID", 80, "Borussia Dortmund", 25),
        ("Serge Gnabry", "FWD", 82, "Bayern Munich", 30),
        ("Karim Adeyemi", "FWD", 81, "Borussia Dortmund", 24),
        ("Nick Woltemade", "FWD", 81, "Newcastle", 24),
        ("Deniz Undav", "FWD", 81, "Stuttgart", 29),
    ],
    "Morocco": [
        ("Munir Mohamedi", "GK", 77, "Al-Wehda", 36),
        ("El Mehdi Benabid", "GK", 74, "Raja Casablanca", 28),
        ("Achraf Dari", "DEF", 78, "Brest", 26),
        ("Romain Saiss", "DEF", 79, "Al-Shabab", 36),
        ("Jawad El Yamiq", "DEF", 78, "Real Valladolid", 33),
        ("Yahya Attiat-Allah", "DEF", 77, "Wydad", 30),
        ("Adam Masina", "DEF", 77, "Torino", 32),
        ("Bilal El Khannouss", "MID", 82, "Stuttgart", 21),
        ("Ilias Chair", "MID", 79, "QPR", 28),
        ("Amir Richardson", "MID", 79, "Fiorentina", 23),
        ("Neil El Aynaoui", "MID", 79, "AS Roma", 24),
        ("Sofiane Boufal", "FWD", 80, "Al-Wakrah", 32),
        ("Soufiane Rahimi", "FWD", 80, "Al-Ain", 29),
        ("Ayoub El Kaabi", "FWD", 81, "Olympiacos", 32),
        ("Eliesse Ben Seghir", "FWD", 80, "Bayer Leverkusen", 20),
        ("Amine Adli", "FWD", 80, "Bournemouth", 25),
        ("Abde Ezzalzouli", "FWD", 81, "Real Betis", 24),
    ],
    "Belgium": [
        ("Koen Casteels", "GK", 82, "Al-Qadsiah", 33),
        ("Matz Sels", "GK", 81, "Nottingham Forest", 33),
        ("Arthur Theate", "DEF", 79, "Eintracht Frankfurt", 25),
        ("Maxim De Cuyper", "DEF", 79, "Brighton", 25),
        ("Brandon Mechele", "DEF", 76, "Club Brugge", 32),
        ("Joaquin Seys", "DEF", 75, "Club Brugge", 20),
        ("Koni De Winter", "DEF", 79, "AC Milan", 23),
        ("Hans Vanaken", "MID", 79, "Club Brugge", 33),
        ("Orel Mangala", "MID", 78, "Everton", 27),
        ("Charles De Ketelaere", "MID", 82, "Atalanta", 24),
        ("Arthur Vermeeren", "MID", 78, "RB Leipzig", 20),
        ("Nicolas Raskin", "MID", 78, "Rangers", 24),
        ("Dodi Lukebakio", "FWD", 80, "Benfica", 28),
        ("Lois Openda", "FWD", 82, "Juventus", 25),
        ("Charles Vanhoutte", "MID", 75, "Marseille", 26),
        ("Maxim Dewaele", "FWD", 73, "Genk", 21),
    ],
    "Croatia": [
        ("Ivica Ivusic", "GK", 77, "Bari", 30),
        ("Nediljko Labrovic", "GK", 75, "Rijeka", 26),
        ("Josip Sutalo", "DEF", 79, "Ajax", 25),
        ("Martin Erlic", "DEF", 77, "Bologna", 28),
        ("Marin Pongracic", "DEF", 78, "Fiorentina", 28),
        ("Borna Sosa", "DEF", 77, "Ajax", 28),
        ("Domagoj Vida", "DEF", 75, "AEK Athens", 37),
        ("Luka Sucic", "MID", 80, "Real Sociedad", 23),
        ("Nikola Vlasic", "MID", 79, "Torino", 28),
        ("Lovro Majer", "MID", 80, "Wolfsburg", 28),
        ("Petar Sucic", "MID", 78, "Inter Milan", 22),
        ("Martin Baturina", "MID", 78, "Como", 23),
        ("Ivan Perisic", "FWD", 80, "PSV", 37),
        ("Mateo Retegui", "FWD", 82, "Al-Qadsiah", 26),
        ("Marco Pasalic", "FWD", 76, "Rijeka", 25),
        ("Igor Matanovic", "FWD", 74, "Eintracht Frankfurt", 22),
        ("Dion Drena Beljo", "FWD", 73, "Augsburg", 23),
        ("Toni Fruk", "MID", 73, "Rijeka", 24),
    ],
    "Colombia": [
        ("David Ospina", "GK", 79, "Atletico Nacional", 37),
        ("Kevin Mier", "GK", 76, "Cruz Azul", 25),
        ("Carlos Cuesta", "DEF", 78, "Galatasaray", 26),
        ("Yerry Mina", "DEF", 78, "Cagliari", 31),
        ("Johan Mojica", "DEF", 77, "Mallorca", 33),
        ("Deiver Machado", "DEF", 76, "Lens", 32),
        ("Santiago Arias", "DEF", 74, "Bahia", 34),
        ("Jefferson Lerma", "MID", 80, "Crystal Palace", 31),
        ("Kevin Castano", "MID", 78, "River Plate", 24),
        ("Jorge Carrascal", "MID", 78, "Flamengo", 27),
        ("Juan Fernando Quintero", "MID", 78, "River Plate", 32),
        ("Mateus Uribe", "MID", 76, "Al-Sadd", 34),
        ("Rafael Santos Borre", "FWD", 78, "Internacional", 30),
        ("Luis Sinisterra", "FWD", 79, "Cruzeiro", 26),
        ("Johan Carbonero", "FWD", 75, "Internacional", 26),
        ("Yaser Asprilla", "MID", 76, "Girona", 22),
        ("Dayro Moreno", "FWD", 73, "Once Caldas", 40),
        ("Jaminton Campaz", "FWD", 73, "Rosario Central", 25),
    ],
    "Uruguay": [
        ("Franco Israel", "GK", 76, "Sporting CP", 25),
        ("Santiago Mele", "GK", 74, "Junior", 28),
        ("Sebastian Caceres", "DEF", 78, "America", 26),
        ("Mathias Olivera", "DEF", 80, "Napoli", 28),
        ("Guillermo Varela", "DEF", 77, "Flamengo", 32),
        ("Nahitan Nandez", "DEF", 77, "Al-Qadsiah", 30),
        ("Santiago Bueno", "DEF", 76, "Wolves", 26),
        ("Rodrigo Bentancur", "MID", 82, "Tottenham", 28),
        ("Giorgian De Arrascaeta", "MID", 82, "Flamengo", 31),
        ("Nicolas Fonseca", "MID", 76, "River Plate", 27),
        ("Emiliano Martinez", "MID", 75, "Penarol", 23),
        ("Maximiliano Araujo", "MID", 77, "Sporting CP", 25),
        ("Rodrigo Aguirre", "FWD", 76, "Penarol", 31),
        ("Cristian Olivera", "FWD", 76, "LAFC", 23),
        ("Brian Rodriguez", "FWD", 77, "America", 25),
        ("Agustin Canobbio", "FWD", 75, "Athletico Paranaense", 27),
        ("Luciano Rodriguez", "FWD", 75, "Bahia", 22),
        ("Rodrigo Zalazar", "MID", 75, "Sporting Braga", 26),
    ],
    "Mexico": [
        ("Guillermo Ochoa", "GK", 78, "AEL Limassol", 40),
        ("Raul Rangel", "GK", 76, "Chivas", 25),
        ("Johan Vasquez", "DEF", 80, "Genoa", 27),
        ("Jorge Sanchez Ramos", "DEF", 74, "Cruz Azul", 28),
        ("Israel Reyes", "DEF", 76, "America", 25),
        ("Kevin Alvarez", "DEF", 76, "America", 26),
        ("Jesus Gallardo", "DEF", 76, "Toluca", 31),
        ("Erik Lira", "MID", 76, "Cruz Azul", 25),
        ("Carlos Rodriguez", "MID", 76, "Cruz Azul", 28),
        ("Marcel Ruiz", "MID", 76, "Toluca", 25),
        ("Gilberto Mora", "MID", 76, "Tijuana", 17),
        ("Orbelin Pineda", "MID", 78, "AEK Athens", 30),
        ("Roberto Alvarado", "FWD", 77, "Chivas", 27),
        ("Alexis Vega", "FWD", 78, "Toluca", 28),
        ("Cesar Huerta", "FWD", 77, "Anderlecht", 25),
        ("Julian Quinones", "FWD", 78, "Al-Qadsiah", 28),
        ("Henry Martin", "FWD", 77, "America", 33),
        ("Diego Lainez", "FWD", 75, "Tigres", 26),
    ],
    "Senegal": [
        ("Mory Diaw", "GK", 75, "Lens", 32),
        ("Yehvann Diouf", "GK", 74, "Reims", 26),
        ("Kalidou Koulibaly_dup", "DEF", 0, "", 0),  # placeholder removed below
        ("Moussa Niakhate", "DEF", 79, "Lyon", 30),
        ("El Hadji Malick Diouf", "DEF", 78, "West Ham", 21),
        ("Antoine Mendy", "DEF", 75, "Nice", 22),
        ("Formose Mendy", "DEF", 75, "Amiens", 25),
        ("Ismail Jakobs", "DEF", 77, "Galatasaray", 26),
        ("Lamine Camara", "MID", 79, "Monaco", 22),
        ("Pape Gueye", "MID", 78, "Villarreal", 27),
        ("Pathe Ciss", "MID", 76, "Rayo Vallecano", 31),
        ("Habib Diarra", "MID", 78, "Sunderland", 22),
        ("Cheikh Sabaly", "MID", 74, "Cadiz", 28),
        ("Boulaye Dia", "FWD", 79, "Lazio", 29),
        ("Iliman Ndiaye", "FWD", 80, "Everton", 26),
        ("Habib Diallo", "FWD", 77, "Al-Shabab", 31),
        ("Cherif Ndiaye", "FWD", 74, "Etoile Sahel", 29),
        ("Chris Gadi", "FWD", 73, "Le Havre", 21),
        ("Krepin Diatta", "MID", 79, "Monaco", 26),
    ],
    "USA": [
        ("Zack Steffen", "GK", 77, "Colorado Rapids", 31),
        ("Patrick Schulte", "GK", 75, "Columbus Crew", 25),
        ("Sergino Dest", "DEF", 80, "PSV", 25),
        ("Tim Ream", "DEF", 76, "Charlotte FC", 38),
        ("Cameron Carter-Vickers", "DEF", 79, "Celtic", 28),
        ("Joe Scally", "DEF", 76, "Borussia Monchengladbach", 23),
        ("Miles Robinson", "DEF", 77, "FC Cincinnati", 29),
        ("Tanner Tessmann", "MID", 76, "Lyon", 24),
        ("Johnny Cardoso", "MID", 79, "Atletico Madrid", 24),
        ("Aidan Morris", "MID", 75, "Middlesbrough", 24),
        ("Malik Tillman", "MID", 80, "Bayer Leverkusen", 23),
        ("Diego Luna", "MID", 75, "Real Salt Lake", 22),
        ("Timothy Weah", "FWD", 79, "Marseille", 25),
        ("Ricardo Pepi", "FWD", 78, "PSV", 22),
        ("Haji Wright", "FWD", 76, "Coventry City", 28),
        ("Brenden Aaronson", "FWD", 77, "Leeds United", 25),
        ("Josh Sargent", "FWD", 78, "Norwich City", 26),
    ],
    "Japan": [
        ("Daiya Maekawa", "GK", 75, "Cerezo Osaka", 29),
        ("Keisuke Osako", "GK", 75, "Sanfrecce Hiroshima", 25),
        ("Hiroki Ito", "DEF", 80, "Bayern Munich", 26),
        ("Shogo Taniguchi", "DEF", 76, "Sint-Truiden", 34),
        ("Yukinari Sugawara", "DEF", 78, "Southampton", 25),
        ("Hiroki Sakai", "DEF", 75, "Urawa Reds", 35),
        ("Kosuke Nakamura", "DEF", 73, "Kashiwa Reysol", 30),
        ("Daichi Kamada", "MID", 81, "Crystal Palace", 29),
        ("Ao Tanaka", "MID", 78, "Leeds United", 27),
        ("Reo Hatate", "MID", 77, "Celtic", 28),
        ("Takumi Minamino", "MID", 80, "Monaco", 31),
        ("Hiroki Abe", "MID", 75, "Kashima Antlers", 26),
        ("Junya Ito", "FWD", 80, "Stade Reims", 32),
        ("Ayase Ueda", "FWD", 79, "Feyenoord", 27),
        ("Daizen Maeda", "FWD", 79, "Celtic", 28),
        ("Koki Ogawa", "FWD", 75, "NEC Nijmegen", 28),
        ("Shuto Machino", "FWD", 76, "Holstein Kiel", 26),
        ("Keito Nakamura", "FWD", 77, "Stade Reims", 25),
    ],
    "Switzerland": [
        ("Gregor Kobel", "GK", 84, "Borussia Dortmund", 28),
        ("Pascal Loretz", "GK", 73, "Luzern", 23),
        ("Ricardo Rodriguez", "DEF", 78, "Real Betis", 33),
        ("Fabian Schar", "DEF", 81, "Newcastle", 34),
        ("Silvan Widmer", "DEF", 77, "Mainz", 33),
        ("Cedric Zesiger", "DEF", 76, "Augsburg", 27),
        ("Aurele Amenda", "DEF", 75, "Eintracht Frankfurt", 22),
        ("Isaac Schmidt", "DEF", 74, "Leeds United", 26),
        ("Denis Zakaria", "MID", 81, "Monaco", 29),
        ("Michel Aebischer", "MID", 78, "Pisa", 29),
        ("Ardon Jashari", "MID", 79, "AC Milan", 23),
        ("Vincent Sierro", "MID", 76, "Al-Sadd", 30),
        ("Fabian Rieder", "MID", 76, "Stuttgart", 24),
        ("Ruben Vargas", "FWD", 79, "Sevilla", 27),
        ("Zeki Amdouni", "FWD", 78, "Benfica", 25),
        ("Johan Manzambi", "FWD", 75, "Freiburg", 20),
        ("Kwadwo Duah", "FWD", 74, "Ludogorets", 28),
        ("Andi Zeqiri", "FWD", 74, "Genoa", 26),
        ("Granit Xhaka_c", "MID", 0, "", 0),  # placeholder removed below
        ("Djibril Sow", "MID", 78, "Sevilla", 29),
    ],
    "Norway": [
        ("Egil Selvik", "GK", 73, "Sarpsborg 08", 33),
        ("Jacob Karlstrom", "GK", 72, "Tromso", 29),
        ("Julian Ryerson", "DEF", 80, "Borussia Dortmund", 28),
        ("David Moller Wolfe", "DEF", 75, "AZ Alkmaar", 23),
        ("Stian Gregersen", "DEF", 76, "Mainz", 31),
        ("Marcus Pedersen", "DEF", 75, "Sassuolo", 25),
        ("Fredrik Bjorkan", "DEF", 74, "Bodo/Glimt", 27),
        ("Andreas Hanche-Olsen", "DEF", 76, "Mainz", 29),
        ("Patrick Berg", "MID", 76, "Bodo/Glimt", 28),
        ("Sander Berge_c", "MID", 0, "", 0),  # placeholder removed below
        ("Fredrik Aursnes", "MID", 79, "Benfica", 30),
        ("Morten Thorsby", "MID", 75, "Genoa", 29),
        ("Mats Moller Daehli", "MID", 75, "St. Pauli", 30),
        ("Antonio Nusa", "FWD", 80, "RB Leipzig", 20),
        ("Oscar Bobb", "FWD", 80, "Manchester City", 22),
        ("Jorgen Strand Larsen", "FWD", 79, "Wolves", 25),
        ("Alexander Sorloth_c", "FWD", 0, "", 0),  # placeholder removed below
        ("Andreas Schjelderup", "FWD", 77, "Benfica", 21),
        ("Thelo Aasgaard", "MID", 75, "Rangers", 23),
        ("Kristian Thorstvedt", "MID", 76, "Sassuolo", 26),
        ("Ola Brynhildsen", "FWD", 73, "Molde", 26),
    ],
    "Turkiye": [
        ("Altay Bayindir", "GK", 78, "Manchester United", 28),
        ("Mert Gunok", "GK", 78, "Besiktas", 36),
        ("Merih Demiral_c", "DEF", 0, "", 0),  # placeholder removed below
        ("Abdulkerim Bardakci", "DEF", 78, "Galatasaray", 31),
        ("Caglar Soyuncu", "DEF", 78, "Fenerbahce", 29),
        ("Samet Akaydin", "DEF", 76, "Eyupspor", 31),
        ("Ferdi Kadioglu", "DEF", 80, "Brighton", 26),
        ("Mert Muldur", "DEF", 76, "Galatasaray", 26),
        ("Eren Elmali", "DEF", 76, "Galatasaray", 25),
        ("Salih Ozcan", "MID", 78, "Borussia Dortmund", 27),
        ("Ismail Yuksek", "MID", 76, "Fenerbahce", 26),
        ("Kerem Akturkoglu", "MID", 80, "Fenerbahce", 27),
        ("Yunus Akgun", "MID", 77, "Galatasaray", 25),
        ("Atakan Karazor", "MID", 75, "Stuttgart", 28),
        ("Kerem Akturkoglu_x", "FWD", 0, "", 0),  # placeholder removed below
        ("Baris Alper Yilmaz", "FWD", 78, "Galatasaray", 25),
        ("Yusuf Yazici", "FWD", 77, "Eyupspor", 28),
        ("Semih Kilicsoy", "FWD", 74, "Besiktas", 20),
        ("Can Uzun", "FWD", 77, "Eintracht Frankfurt", 19),
        ("Deniz Gul", "FWD", 73, "Porto", 21),
        ("Cenk Tosun", "FWD", 75, "Besiktas", 34),
    ],
    "Ecuador": [
        ("Alexander Dominguez", "GK", 76, "LDU Quito", 38),
        ("Gonzalo Valle", "GK", 73, "LDU Quito", 26),
        ("Felix Torres", "DEF", 77, "Corinthians", 28),
        ("Joel Ordonez", "DEF", 79, "Club Brugge", 21),
        ("Xavier Arreaga", "DEF", 74, "Austin FC", 31),
        ("Pervis Estupinan", "DEF", 80, "AC Milan", 28),
        ("Angelo Preciado", "DEF", 76, "Sparta Prague", 27),
        ("Alan Franco", "MID", 76, "LDU Quito", 26),
        ("Jhegson Mendez", "MID", 76, "Leon", 28),
        ("Carlos Gruezo", "MID", 75, "Lanus", 30),
        ("Alan Minda", "MID", 74, "Cercle Brugge", 22),
        ("Patrik Mercado", "MID", 73, "LDU Quito", 23),
        ("Gonzalo Plata", "FWD", 79, "Flamengo", 25),
        ("Kevin Rodriguez", "FWD", 76, "Union Saint-Gilloise", 25),
        ("Leonardo Campana", "FWD", 75, "Inter Miami", 25),
        ("Nilson Angulo", "FWD", 74, "Anderlecht", 22),
        ("John Yeboah", "FWD", 73, "Slavia Prague", 25),
        ("Jeremy Sarmiento", "FWD", 75, "Burnley", 23),
        ("Pedro Vite", "MID", 73, "Vancouver Whitecaps", 23),
        ("Denil Castillo", "MID", 72, "Norwich City", 24),
    ],
    "Austria": [
        ("Niklas Hedl", "GK", 76, "Rapid Vienna", 24),
        ("Heinz Lindner", "GK", 74, "Union Saint-Gilloise", 35),
        ("Maximilian Wober", "DEF", 78, "Borussia Monchengladbach", 28),
        ("Philipp Lienhart", "DEF", 77, "Freiburg", 29),
        ("Gernot Trauner", "DEF", 76, "Feyenoord", 34),
        ("Stefan Posch", "DEF", 76, "Bologna", 29),
        ("Phillipp Mwene", "DEF", 75, "Mainz", 32),
        ("Flavius Daniliuc", "DEF", 74, "Salernitana", 24),
        ("Leopold Querfeld", "DEF", 74, "Union Berlin", 22),
        ("Florian Grillitsch", "MID", 77, "Hoffenheim", 30),
        ("Romano Schmid", "MID", 76, "Werder Bremen", 26),
        ("Patrick Wimmer", "MID", 76, "Wolfsburg", 25),
        ("Matthias Seidl", "MID", 74, "Rapid Vienna", 25),
        ("Michael Gregoritsch", "FWD", 77, "Freiburg", 32),
        ("Marko Arnautovic_c", "FWD", 0, "", 0),  # placeholder removed below
        ("Maximilian Entrup", "FWD", 73, "Hamburger SV", 28),
        ("Junior Adamu", "FWD", 74, "Freiburg", 24),
        ("Romeo Vucic", "FWD", 72, "Rapid Vienna", 20),
        ("Sasa Kalajdzic", "FWD", 75, "Hamburger SV", 28),
    ],
    "South Korea": [
        ("Jo Hyeon-woo", "GK", 78, "Ulsan HD", 34),
        ("Song Bum-keun", "GK", 74, "Jeonbuk", 28),
        ("Kim Ji-soo", "DEF", 75, "Daejeon Hana", 21),
        ("Kim Moon-hwan", "DEF", 74, "Daejeon Hana", 30),
        ("Lee Tae-seok", "DEF", 73, "Suwon FC", 25),
        ("Cho Yu-min", "DEF", 75, "Sharjah", 29),
        ("Seol Young-woo", "DEF", 74, "Ulsan HD", 27),
        ("Park Yong-woo", "MID", 75, "Al-Ain", 33),
        ("Hong Hyun-seok", "MID", 76, "Mainz", 26),
        ("Lee Jae-sung", "MID", 78, "Mainz", 33),
        ("Paik Seung-ho", "MID", 75, "Birmingham City", 28),
        ("Won Du-jae", "MID", 74, "Jeonbuk", 28),
        ("Kang Sang-woo", "DEF", 73, "Beijing Guoan", 27),
        ("Oh Hyeon-gyu", "FWD", 76, "Genk", 24),
        ("Cho Gue-sung", "FWD", 76, "Midtjylland", 27),
        ("Hwang Ui-jo", "FWD", 75, "Alanyaspor", 33),
        ("Bae Jun-ho", "MID", 76, "Stoke City", 22),
        ("Eom Ji-sung", "FWD", 73, "Swansea City", 23),
        ("Lee Dong-gyeong", "MID", 74, "Gimcheon Sangmu", 29),
    ],
    "Australia": [
        ("Joe Gauci", "GK", 74, "Aston Villa", 25),
        ("Paul Izzo", "GK", 72, "Randers", 31),
        ("Kye Rowles", "DEF", 75, "Hearts", 27),
        ("Cameron Burgess", "DEF", 74, "Ipswich Town", 30),
        ("Milos Degenek", "DEF", 73, "Al-Ittihad", 31),
        ("Aziz Behich", "DEF", 74, "Melbourne City", 35),
        ("Lewis Miller", "DEF", 72, "Hibernian", 25),
        ("Jordan Bos", "DEF", 76, "Feyenoord", 23),
        ("Connor Metcalfe", "MID", 74, "St. Pauli", 26),
        ("Riley McGree", "MID", 75, "Middlesbrough", 27),
        ("Keanu Baccus", "MID", 73, "St. Mirren", 28),
        ("Cameron Devlin", "MID", 72, "Hearts", 28),
        ("Ajdin Hrustic", "MID", 73, "NAC Breda", 30),
        ("Nestory Irankunda", "FWD", 75, "Watford", 20),
        ("Kusini Yengi", "FWD", 73, "Portsmouth", 27),
        ("Adam Taggart", "FWD", 73, "Perth Glory", 33),
        ("Bruno Fornaroli", "FWD", 73, "Melbourne Victory", 38),
        ("Mohamed Toure", "FWD", 71, "Randers", 21),
        ("Sammy Silvera", "FWD", 72, "Middlesbrough", 25),
        ("Patrick Yazbek", "MID", 72, "Viking", 23),
    ],
    "Algeria": [
        ("Alexandre Oukidja", "GK", 75, "Metz", 37),
        ("Anthony Mandrea", "GK", 73, "Angers", 28),
        ("Youcef Atal", "DEF", 77, "Al-Sadd", 29),
        ("Mohamed Amine Tougai", "DEF", 75, "Esperance", 24),
        ("Jaouen Hadjam", "DEF", 75, "Young Boys", 22),
        ("Ahmed Touba", "DEF", 74, "Lens", 27),
        ("Rayan Ait-Nouri", "DEF", 80, "Manchester City", 24),
        ("Houssem Aouar", "MID", 78, "Al-Ittihad", 27),
        ("Nabil Bentaleb", "MID", 76, "Lille", 31),
        ("Ramiz Zerrouki", "MID", 76, "Feyenoord", 27),
        ("Adam Ounas", "MID", 75, "Trabzonspor", 29),
        ("Hicham Boudaoui", "MID", 75, "Nice", 26),
        ("Ibrahim Maza", "MID", 76, "Bayer Leverkusen", 20),
        ("Amine Gouiri", "FWD", 80, "Marseille", 26),
        ("Mohamed Amoura", "FWD", 80, "Wolfsburg", 25),
        ("Baghdad Bounedjah", "FWD", 76, "Al-Sadd", 34),
        ("Yacine Brahimi", "FWD", 76, "Al-Gharafa", 35),
        ("Farès Chaibi", "MID", 77, "Eintracht Frankfurt", 23),
        ("Badredine Bouanani", "FWD", 74, "Sunderland", 21),
        ("Anis Hadj Moussa", "FWD", 75, "Feyenoord", 23),
    ],
    "Egypt": [
        ("Mohamed Sobhi", "GK", 73, "Pyramids", 27),
        ("Mohamed Abou Gabal", "GK", 74, "Al-Ittihad Alex", 36),
        ("Ahmed Hegazi", "DEF", 76, "Al-Ittihad", 34),
        ("Mohamed Hany", "DEF", 73, "Al Ahly", 30),
        ("Ahmed Fattouh", "DEF", 73, "Zamalek", 28),
        ("Omar Kamal", "DEF", 73, "Al Ahly", 26),
        ("Rami Rabia", "DEF", 73, "Al Ahly", 32),
        ("Mohamed Hamdy", "DEF", 72, "Pyramids", 28),
        ("Hamdi Fathi", "MID", 75, "Wydad", 31),
        ("Nabil Emad Donga", "MID", 73, "Pyramids", 25),
        ("Mahmoud Saber", "MID", 73, "Al Ahly", 24),
        ("Marwan Attia", "MID", 73, "Al Ahly", 25),
        ("Emam Ashour", "MID", 77, "Al Ahly", 27),
        ("Mostafa Mohamed", "FWD", 78, "Nantes", 28),
        ("Mohamed Sherif", "FWD", 74, "Al Ahly", 28),
        ("Ibrahim Adel", "FWD", 75, "Pyramids", 24),
        ("Ahmed Sayed Zizo", "FWD", 76, "Al Ahly", 29),
        ("Mahmoud Hassan Trezeguet_c", "FWD", 0, "", 0),  # placeholder removed below
        ("Mahmoud Saleh", "MID", 72, "Zamalek", 24),
        ("Osama Faisal", "FWD", 72, "Al-Bahaa", 26),
        ("Mohamed Magdy Afsha", "MID", 75, "Al Ahly", 31),
    ],
    "Iran": [
        ("Payam Niazmand", "GK", 75, "Sepahan", 30),
        ("Hossein Hosseini", "GK", 73, "Esteghlal", 33),
        ("Sadegh Moharrami", "DEF", 74, "Dinamo Zagreb", 29),
        ("Aref Aghasi", "DEF", 73, "Sepahan", 25),
        ("Majid Hosseini", "DEF", 74, "Kayserispor", 29),
        ("Hossein Kanaani", "DEF", 73, "Al-Sharjah", 31),
        ("Milad Mohammadi", "DEF", 73, "Persepolis", 32),
        ("Ramin Rezaeian", "DEF", 74, "Esteghlal", 35),
        ("Omid Noorafkan", "DEF", 72, "Sepahan", 28),
        ("Ahmad Nourollahi", "MID", 75, "Shabab Al-Ahli", 32),
        ("Mehdi Torabi", "MID", 74, "Persepolis", 31),
        ("Ali Karimi", "MID", 73, "Esteghlal", 31),
        ("Mohammad Mohebi", "FWD", 74, "Rostov", 27),
        ("Karim Ansarifard", "FWD", 73, "Omonia", 35),
        ("Allahyar Sayyadmanesh", "FWD", 74, "Westerlo", 24),
        ("Shahriyar Moghanlou", "FWD", 73, "Persepolis", 28),
        ("Mehdi Ghayedi", "FWD", 74, "Ittihad Kalba", 27),
        ("Mohammad Ghaderi", "MID", 72, "Tractor", 25),
        ("Saeid Sadeghi", "MID", 72, "Sepahan", 30),
    ],
    "Canada": [
        ("Dayne St. Clair", "GK", 77, "Minnesota United", 28),
        ("Tom McGill", "GK", 72, "Brighton", 25),
        ("Kamal Miller", "DEF", 75, "Portland Timbers", 28),
        ("Derek Cornelius", "DEF", 76, "Marseille", 28),
        ("Joel Waterman", "DEF", 73, "CF Montreal", 29),
        ("Alistair Johnston", "DEF", 78, "Celtic", 27),
        ("Richie Laryea", "DEF", 74, "Toronto FC", 31),
        ("Luc de Fougerolles", "DEF", 73, "Fulham", 20),
        ("Ismael Kone", "MID", 76, "Sassuolo", 23),
        ("Mathieu Choiniere", "MID", 74, "Grasshoppers", 26),
        ("Liam Fraser", "MID", 72, "Deinze", 27),
        ("Nathan Saliba", "MID", 73, "Anderlecht", 21),
        ("Jonathan Osorio", "MID", 75, "Toronto FC", 33),
        ("Tani Oluwaseyi", "FWD", 74, "Minnesota United", 25),
        ("Jacob Shaffelburg", "FWD", 74, "Nashville SC", 26),
        ("Theo Bair", "FWD", 73, "Saint-Etienne", 26),
        ("Jonathan David_c", "FWD", 0, "", 0),  # placeholder removed below
        ("Promise David", "FWD", 74, "Union Saint-Gilloise", 24),
        ("Daniel Jebbison", "FWD", 73, "Bournemouth", 22),
        ("Samuel Piette", "MID", 73, "CF Montreal", 31),
    ],
    "Ivory Coast": [
        ("Yahia Fofana_c", "GK", 0, "", 0),  # placeholder removed below
        ("Badra Ali Sangare", "GK", 73, "Esperance", 32),
        ("Mohamed Kone", "GK", 71, "Stade Tunisien", 24),
        ("Willy Boly", "DEF", 76, "Al-Shabab", 35),
        ("Ousmane Diomande", "DEF", 80, "Sporting CP", 22),
        ("Wilfried Singo", "DEF", 80, "Monaco", 25),
        ("Ghislain Konan", "DEF", 74, "Al-Wahda", 30),
        ("Emmanuel Agbadou", "DEF", 77, "Wolves", 28),
        ("Yan Diomande", "MID", 76, "RB Leipzig", 20),
        ("Ibrahim Sangare", "MID", 79, "Nottingham Forest", 28),
        ("Jean Michael Seri", "MID", 76, "Al-Arabi", 34),
        ("Lazare Amani", "MID", 73, "Union Saint-Gilloise", 27),
        ("Jean-Philippe Krasso", "FWD", 74, "Panathinaikos", 28),
        ("Nicolas Pepe", "FWD", 77, "Villarreal", 30),
        ("Jeremie Boga", "MID", 77, "Nice", 28),
        ("Christian Kouame", "FWD", 75, "Fiorentina", 28),
        ("Amad Diallo", "FWD", 81, "Manchester United", 23),
        ("Karim Konate", "FWD", 75, "Red Bull Salzburg", 21),
        ("Oumar Diakite", "FWD", 73, "Reims", 22),
        ("Franck Kessie_c", "MID", 0, "", 0),  # placeholder removed below
        ("Seko Fofana_c", "MID", 0, "", 0),  # placeholder removed below
        ("Hamed Traore", "MID", 76, "Auxerre", 26),
    ],
    "Sweden": [
        ("Kristoffer Nordfeldt", "GK", 74, "AIK", 36),
        ("Robin Olsen_c", "GK", 0, "", 0),  # placeholder removed below
        ("Jacob Rinne", "GK", 72, "Norrkoping", 32),
        ("Isak Hien", "DEF", 80, "Atalanta", 26),
        ("Gabriel Gudmundsson", "DEF", 77, "Leeds United", 26),
        ("Hjalmar Ekdal", "DEF", 74, "Burnley", 27),
        ("Daniel Svensson", "DEF", 75, "Borussia Dortmund", 23),
        ("Samuel Dahl", "DEF", 74, "AS Roma", 22),
        ("Carl Starfelt", "DEF", 75, "Celta Vigo", 30),
        ("Lucas Bergvall", "MID", 80, "Tottenham", 19),
        ("Yasin Ayari", "MID", 77, "Brighton", 22),
        ("Hugo Larsson", "MID", 80, "Eintracht Frankfurt", 21),
        ("Jens Cajuste", "MID", 77, "Ipswich Town", 26),
        ("Mattias Svanberg", "MID", 77, "Wolfsburg", 27),
        ("Albin Ekdal", "MID", 73, "Spezia", 36),
        ("Emil Forsberg", "FWD", 78, "New York Red Bulls", 34),
        ("Anthony Elanga_c", "FWD", 0, "", 0),  # placeholder removed below
        ("Roony Bardghji", "FWD", 76, "Barcelona", 20),
        ("Jesper Karlsson", "FWD", 76, "Lens", 27),
        ("Gustaf Nilsson", "FWD", 73, "Union Saint-Gilloise", 28),
        ("Kristoffer Olsson", "MID", 76, "FC Copenhagen", 30),
    ],
    "Czechia": [
        ("Matej Kovar", "GK", 77, "Bayer Leverkusen", 25),
        ("Vitezslav Jaros", "GK", 75, "Ajax", 24),
        ("Tomas Vlcek", "DEF", 73, "Slavia Prague", 24),
        ("Robin Hranac", "DEF", 76, "Hoffenheim", 26),
        ("Tomas Holes", "DEF", 75, "Slavia Prague", 32),
        ("David Zima", "DEF", 74, "Slavia Prague", 25),
        ("Vladimir Coufal", "DEF", 76, "Hoffenheim", 33),
        ("Martin Vitik", "DEF", 75, "Sparta Prague", 22),
        ("David Jurasek", "DEF", 75, "Hoffenheim", 25),
        ("Pavel Sulc", "MID", 78, "PSV", 25),
        ("Lukas Provod", "MID", 78, "Slavia Prague", 29),
        ("Michal Sadilek", "MID", 74, "Twente", 26),
        ("Vaclav Cerny", "FWD", 78, "Rangers", 28),
        ("Adam Karabec", "MID", 74, "Lyon", 22),
        ("Tomas Chory", "FWD", 75, "Viktoria Plzen", 30),
        ("Mojmir Chytil", "FWD", 73, "Slavia Prague", 27),
        ("Vasil Kusej", "FWD", 74, "Mlada Boleslav", 27),
        ("Ondrej Lingr", "FWD", 74, "Feyenoord", 27),
        ("Antonin Barak_c", "MID", 0, "", 0),  # placeholder removed below
        ("Michal Sevcik", "MID", 74, "Birmingham City", 23),
    ],
    "Ghana": [
        ("Benjamin Asare", "GK", 72, "Hearts of Oak", 29),
        ("Joseph Wollacott", "GK", 73, "Crawley Town", 29),
        ("Mohammed Salisu", "DEF", 79, "Monaco", 26),
        ("Alidu Seidu", "DEF", 76, "Rennes", 25),
        ("Gideon Mensah", "DEF", 74, "Lille", 27),
        ("Jerome Opoku", "DEF", 73, "Istanbul Basaksehir", 27),
        ("Kingsley Schindler", "DEF", 72, "Samsunspor", 32),
        ("Razak Simpson", "DEF", 72, "Nordsjaelland", 23),
        ("Elisha Owusu", "MID", 75, "Auxerre", 28),
        ("Salis Abdul Samed", "MID", 76, "Sunderland", 25),
        ("Lawrence Agyekum", "MID", 74, "Cercle Brugge", 22),
        ("Kwasi Sibo", "MID", 73, "Eldense", 27),
        ("Majeed Ashimeru", "MID", 74, "Anderlecht", 28),
        ("Ernest Nuamah", "FWD", 78, "Lyon", 22),
        ("Kamaldeen Sulemana", "FWD", 78, "Atalanta", 24),
        ("Fatawu Issahaku", "FWD", 77, "Leicester City", 21),
        ("Brandon Thomas-Asante", "FWD", 74, "Coventry City", 27),
        ("Joseph Paintsil", "FWD", 76, "LA Galaxy", 28),
        ("Christopher Bonsu Baah", "FWD", 73, "Genk", 22),
    ],
    "Bosnia-Herzegovina": [
        ("Nikola Vasilj", "GK", 76, "St. Pauli", 30),
        ("Vladan Kovacevic", "GK", 76, "Sporting CP", 27),
        ("Dennis Hadzikadunic", "DEF", 74, "Rostov", 27),
        ("Nihad Mujakic", "DEF", 73, "Buyuksehir Belediye", 27),
        ("Amar Dedic", "DEF", 78, "Benfica", 23),
        ("Adnan Kovacevic", "DEF", 73, "Kayserispor", 32),
        ("Dzenis Burnic", "DEF", 73, "Sturm Graz", 27),
        ("Ajdin Hasic", "MID", 73, "Hajduk Split", 24),
        ("Gojko Cimirot", "MID", 74, "PAOK", 33),
        ("Benjamin Tahirovic", "MID", 76, "Ajax", 22),
        ("Amar Begic", "MID", 72, "Sturm Graz", 23),
        ("Ivan Basic", "MID", 72, "Sturm Graz", 25),
        ("Edon Zhegrova", "FWD", 79, "Juventus", 26),
        ("Smail Prevljak", "FWD", 74, "Al-Wakrah", 31),
        ("Haris Tabakovic", "FWD", 76, "Hoffenheim", 31),
        ("Said Hamulic", "FWD", 73, "Toulouse", 25),
        ("Armin Gigovic", "MID", 73, "Rostov", 23),
        ("Dal Varesanovic", "MID", 72, "Pescara", 24),
        ("Nemanja Bilbija", "FWD", 71, "Zrinjski", 35),
        ("Kenan Kodro", "FWD", 72, "Pafos", 32),
        ("Luka Menalo", "FWD", 72, "Dinamo Zagreb", 29),
    ],
    "Paraguay": [
        ("Carlos Coronel", "GK", 75, "New York Red Bulls", 29),
        ("Orlando Gill", "GK", 72, "Cerro Porteno", 26),
        ("Junior Alonso", "DEF", 77, "Atletico Mineiro", 32),
        ("Fabian Balbuena", "DEF", 75, "Corinthians", 34),
        ("Juan Caceres", "DEF", 73, "Argentinos Juniors", 28),
        ("Agustin Sandez", "DEF", 74, "Boca Juniors", 24),
        ("Alan Benitez", "DEF", 73, "Cerro Porteno", 31),
        ("Andres Cubas", "MID", 76, "Vancouver Whitecaps", 29),
        ("Mathias Villasanti", "MID", 76, "Gremio", 28),
        ("Damian Bobadilla", "MID", 74, "Sao Paulo", 22),
        ("Diego Gomez", "MID", 77, "Brighton", 22),
        ("Ramon Sosa", "FWD", 77, "Nottingham Forest", 25),
        ("Matias Galarza", "MID", 73, "Talleres", 23),
        ("Gabriel Avalos", "FWD", 73, "Independiente", 34),
        ("Adam Bareiro", "FWD", 75, "River Plate", 29),
        ("Damian Martinez", "FWD", 72, "Cerro Porteno", 27),
        ("Ronaldo Martinez", "FWD", 72, "Newells", 28),
        ("Isidro Pitta", "FWD", 73, "Bragantino", 24),
        ("Hernesto Caballero", "MID", 72, "Cerro Porteno", 24),
        ("Wilder Viera", "MID", 71, "Libertad", 25),
    ],
    "Scotland": [
        ("Craig Gordon", "GK", 75, "Hearts", 43),
        ("Cieran Slicker", "GK", 71, "Ipswich Town", 23),
        ("Jack Hendry", "DEF", 76, "Al-Ettifaq", 30),
        ("Grant Hanley", "DEF", 74, "Birmingham City", 34),
        ("Ryan Porteous", "DEF", 74, "Watford", 26),
        ("Scott McKenna", "DEF", 75, "Las Palmas", 29),
        ("Anthony Ralston", "DEF", 73, "Celtic", 27),
        ("Max Johnston", "DEF", 73, "Sturm Graz", 22),
        ("Aaron Hickey", "DEF", 76, "Brentford", 23),
        ("Ryan Christie", "MID", 76, "Bournemouth", 31),
        ("Kenny McLean", "MID", 74, "Norwich City", 34),
        ("Lewis Ferguson", "MID", 78, "Bologna", 26),
        ("Connor Barron", "MID", 73, "Rangers", 23),
        ("Ben Doak", "FWD", 77, "Bournemouth", 20),
        ("Lyndon Dykes", "FWD", 74, "Birmingham City", 30),
        ("Lawrence Shankland", "FWD", 75, "Hearts", 30),
        ("George Hirst", "FWD", 73, "Ipswich Town", 26),
        ("Tommy Conway", "FWD", 73, "Middlesbrough", 23),
        ("James Wilson", "FWD", 71, "Hearts", 19),
    ],
    "Tunisia": [
        ("Bechir Ben Said", "GK", 73, "US Monastir", 30),
        ("Noureddine Farhati", "GK", 71, "Esperance", 32),
        ("Yassine Meriah", "DEF", 74, "Esperance", 32),
        ("Dylan Bronn", "DEF", 75, "Salernitana", 30),
        ("Mohamed Drager", "DEF", 73, "Karagumruk", 29),
        ("Wajdi Kechrida", "DEF", 73, "Atromitos", 29),
        ("Yan Valery", "DEF", 73, "Sochaux", 27),
        ("Ali Maaloul", "DEF", 74, "Al Ahly", 35),
        ("Mortadha Ben Ouanes", "DEF", 72, "Yverdon", 30),
        ("Ferjani Sassi", "MID", 74, "Al-Duhail", 33),
        ("Mohamed Ali Ben Romdhane", "MID", 75, "Ferencvaros", 26),
        ("Ellyes Skhiri", "MID", 79, "Eintracht Frankfurt", 30),
        ("Ghailene Chaalali", "MID", 72, "Esperance", 31),
        ("Hamza Rafia", "MID", 73, "Lecce", 26),
        ("Naim Sliti", "FWD", 75, "Al-Ettifaq", 33),
        ("Seifeddine Jaziri", "FWD", 73, "Zamalek", 32),
        ("Firas Chaouat", "FWD", 72, "Esperance", 28),
        ("Omar Layouni", "FWD", 72, "Esperance", 27),
        ("Haythem Jouini", "FWD", 71, "Esperance", 29),
    ],
    "DR Congo": [
        ("Timothy Fayulu", "GK", 73, "Sion", 29),
        ("Dimitry Bertaud", "GK", 73, "Montpellier", 27),
        ("Gedeon Kalulu", "DEF", 74, "Lorient", 28),
        ("Aaron Wan-Bissaka", "DEF", 80, "West Ham", 28),
        ("Axel Tuanzebe", "DEF", 74, "Burnley", 28),
        ("Rocky Bushiri", "DEF", 73, "Hibernian", 26),
        ("Joris Kayembe", "DEF", 73, "Genk", 31),
        ("Dylan Batubinsika", "DEF", 73, "Saint-Etienne", 29),
        ("Edo Kayembe", "MID", 75, "Watford", 28),
        ("Samuel Moutoussamy", "MID", 74, "Nantes", 29),
        ("Charles Pickel_c", "MID", 0, "", 0),  # placeholder removed below
        ("Aron Donnum", "MID", 73, "Standard Liege", 27),
        ("Noah Sadiki", "MID", 76, "Sunderland", 21),
        ("Theo Bongonda", "FWD", 76, "Spartak Moscow", 30),
        ("Meschack Elia", "FWD", 74, "Young Boys", 28),
        ("Fiston Mayele", "FWD", 76, "Pyramids", 31),
        ("Simon Banza", "FWD", 76, "Trabzonspor", 29),
        ("Chadrack Lukombe", "DEF", 71, "Eupen", 26),
        ("Brian Cipenga", "MID", 71, "Lommel", 22),
        ("Grady Diangana", "MID", 74, "West Brom", 28),
    ],
    "Qatar": [
        ("Saad Al-Sheeb", "GK", 73, "Al-Sadd", 35),
        ("Yousef Hassan", "GK", 71, "Al-Gharafa", 29),
        ("Tarek Salman", "DEF", 73, "Al-Sadd", 28),
        ("Bassam Al-Rawi", "DEF", 73, "Al-Duhail", 28),
        ("Pedro Miguel", "DEF", 73, "Al-Sadd", 35),
        ("Jassem Gaber", "DEF", 72, "Al-Arabi", 26),
        ("Sultan Al-Brake", "DEF", 72, "Al-Duhail", 28),
        ("Homam Ahmed", "DEF", 71, "Al-Gharafa", 26),
        ("Karim Boudiaf", "MID", 73, "Al-Shamal", 35),
        ("Abdulaziz Hatem", "MID", 72, "Al-Rayyan", 35),
        ("Mostafa Meshaal", "MID", 73, "Al-Sadd", 25),
        ("Ahmed Fadel", "MID", 71, "Al-Sadd", 23),
        ("Jassem Al-Sharshani", "MID", 71, "Al-Gharafa", 24),
        ("Tameem Al-Muhaza", "FWD", 72, "Al-Sadd", 24),
        ("Mohammed Muntari", "FWD", 71, "Al-Duhail", 32),
        ("Yusuf Abdurisag", "FWD", 72, "Al-Sadd", 26),
        ("Ahmed Alaaeldin", "FWD", 71, "Al-Gharafa", 32),
        ("Khaled Muneer", "FWD", 70, "Al-Wakrah", 23),
        ("Naif Al-Hadhrami", "MID", 70, "Al-Rayyan", 24),
        ("Hashim Ali", "DEF", 70, "Al-Duhail", 24),
        ("Ahmed Suhail", "FWD", 70, "Al-Sadd", 23),
    ],
    "Saudi Arabia": [
        ("Nawaf Al-Aqidi", "GK", 73, "Al-Nassr", 25),
        ("Ahmed Al-Kassar", "GK", 71, "Al-Ittihad", 27),
        ("Hassan Tambakti", "DEF", 75, "Al-Hilal", 26),
        ("Ali Al-Boleahi", "DEF", 73, "Al-Hilal", 36),
        ("Saud Abdulhamid", "DEF", 75, "Lens", 26),
        ("Sultan Al-Ghanam", "DEF", 73, "Al-Nassr", 31),
        ("Abdullah Madu", "DEF", 72, "Al-Nassr", 32),
        ("Yasser Al-Shahrani", "DEF", 73, "Al-Hilal", 33),
        ("Nasser Al-Dawsari", "MID", 74, "Al-Hilal", 27),
        ("Mohamed Kanno", "MID", 75, "Al-Hilal", 31),
        ("Abdulelah Al-Malki", "MID", 74, "Al-Hilal", 30),
        ("Ali Al-Hassan", "MID", 73, "Al-Nassr", 28),
        ("Musab Al-Juwayr", "MID", 74, "Al-Hilal", 21),
        ("Sultan Al-Ammari", "MID", 72, "Al-Ahli", 27),
        ("Saleh Al-Shehri", "FWD", 75, "Al-Hilal", 32),
        ("Abdullah Al-Hamdan", "FWD", 73, "Al-Hilal", 26),
        ("Saud Al-Nashri", "FWD", 72, "Al-Taawoun", 21),
        ("Marwan Al-Sahafi", "FWD", 71, "Al-Ahli", 24),
        ("Abdulrahman Ghareeb", "FWD", 73, "Al-Nassr", 28),
        ("Hattan Bahebri", "FWD", 72, "Al-Shabab", 33),
        ("Ayman Yahya", "MID", 72, "Al-Nassr", 24),
    ],
    "South Africa": [
        ("Ronwen Williams_c", "GK", 0, "", 0),  # placeholder removed below
        ("Sipho Chaine", "GK", 72, "Orlando Pirates", 27),
        ("Ricardo Goss", "GK", 70, "Sekhukhune United", 30),
        ("Nkosinathi Sibisi", "DEF", 72, "Orlando Pirates", 28),
        ("Mothobi Mvala", "DEF", 73, "Mamelodi Sundowns", 31),
        ("Khuliso Mudau", "DEF", 73, "Mamelodi Sundowns", 30),
        ("Aubrey Modiba", "DEF", 73, "Mamelodi Sundowns", 30),
        ("Nyiko Mobbie", "DEF", 71, "Mamelodi Sundowns", 25),
        ("Grant Kekana", "DEF", 71, "Mamelodi Sundowns", 33),
        ("Thapelo Morena", "DEF", 72, "Mamelodi Sundowns", 32),
        ("Teboho Mokoena_c", "MID", 0, "", 0),  # placeholder removed below
        ("Sphephelo Sithole", "MID", 73, "Tondela", 26),
        ("Bongani Zungu", "MID", 72, "Mamelodi Sundowns", 33),
        ("Themba Zwane", "MID", 73, "Mamelodi Sundowns", 36),
        ("Thalente Mbatha", "MID", 71, "Orlando Pirates", 27),
        ("Patrick Maswanganyi", "MID", 73, "Orlando Pirates", 24),
        ("Relebohile Mofokeng", "FWD", 75, "Orlando Pirates", 21),
        ("Oswin Appollis", "FWD", 73, "Polokwane City", 24),
        ("Mihlali Mayambela", "FWD", 71, "Aris Limassol", 29),
        ("Iqraam Rayners", "FWD", 73, "Mamelodi Sundowns", 30),
        ("Evidence Makgopa", "FWD", 72, "Orlando Pirates", 25),
        ("Tashreeq Morris", "FWD", 71, "Sekhukhune United", 30),
        ("Ethan Brooks", "MID", 71, "Toulouse", 24),
    ],
    "Iraq": [
        ("Ahmad Basil", "GK", 71, "Al-Shorta", 25),
        ("Fahad Talib", "GK", 71, "Al-Quwa Al-Jawiya", 30),
        ("Merchas Doski", "DEF", 73, "Duhok", 26),
        ("Zaid Tahseen", "DEF", 71, "Al-Quwa Al-Jawiya", 27),
        ("Akam Hashim", "DEF", 71, "Al-Shorta", 28),
        ("Hussein Ali", "DEF", 72, "Persepolis", 24),
        ("Mustafa Nadhim", "DEF", 71, "Al-Shorta", 25),
        ("Saad Natiq", "DEF", 71, "Al-Najaf", 33),
        ("Manaf Younis", "MID", 72, "Al-Quwa Al-Jawiya", 25),
        ("Ibrahim Bayesh", "MID", 72, "Al-Shorta", 28),
        ("Bashar Resan", "MID", 73, "Al-Gharafa", 29),
        ("Osama Rashid", "MID", 72, "Goztepe", 33),
        ("Zidane Iqbal", "MID", 74, "Utrecht", 23),
        ("Youssef Amyn", "FWD", 73, "Karagumruk", 24),
        ("Ali Jasim", "FWD", 73, "Como", 22),
        ("Mohanad Ali", "FWD", 75, "Al-Duhail", 26),
        ("Ahmed Yahya", "FWD", 71, "Al-Quwa Al-Jawiya", 24),
        ("Ali Hussein Rehema", "DEF", 70, "Al-Karkh", 24),
        ("Sajjad Jassim", "MID", 70, "Al-Quwa Al-Jawiya", 24),
        ("Hasan Abdulkareem", "FWD", 70, "Al-Shorta", 23),
        ("Amjad Attwan", "MID", 72, "Al-Quwa Al-Jawiya", 27),
    ],
    "Uzbekistan": [
        ("Botirali Ergashev", "GK", 71, "Navbahor", 28),
        ("Abduvohid Nematov", "GK", 70, "Pakhtakor", 27),
        ("Rustamjon Ashurmatov", "DEF", 73, "Gangwon", 30),
        ("Abdukodir Khusanov_c", "DEF", 0, "", 0),  # placeholder removed below
        ("Farrukh Sayfiev", "DEF", 72, "Pakhtakor", 28),
        ("Sherzod Nasrullaev", "DEF", 71, "Pakhtakor", 27),
        ("Khojiakbar Alijonov", "DEF", 72, "Pakhtakor", 27),
        ("Abdullaev Abbosbek", "DEF", 70, "Navbahor", 25),
        ("Umarali Rakhmonaliev", "MID", 72, "Pakhtakor", 27),
        ("Otabek Shukurov", "MID", 73, "Al-Wakrah", 29),
        ("Jasurbek Jaloliddinov", "MID", 73, "Lokomotiv Moscow", 24),
        ("Azizbek Turgunboev", "MID", 72, "Pakhtakor", 31),
        ("Oston Urunov", "MID", 72, "Neftchi", 25),
        ("Abbosbek Fayzullaev_c", "MID", 0, "", 0),  # placeholder removed below
        ("Igor Sergeev", "FWD", 73, "Pakhtakor", 32),
        ("Bobir Abdixolikov", "FWD", 73, "Al-Najma", 27),
        ("Khusayin Norchaev", "FWD", 72, "Pakhtakor", 25),
        ("Shukrullo Yusupov", "MID", 70, "Pakhtakor", 22),
        ("Diyor Kholmatov", "FWD", 70, "Andijan", 23),
        ("Ulugbek Khoshimov", "FWD", 70, "AGMK", 26),
        ("Jasurbek Yakhshiboev", "FWD", 72, "Slovan Bratislava", 28),
        ("Sherzodbek Urozboev", "DEF", 70, "Pakhtakor", 23),
        ("Khusniddin Alikulov", "DEF", 72, "Pakhtakor", 26),
    ],
    "Panama": [
        ("Cesar Samudio", "GK", 72, "Independiente FBC", 30),
        ("Luis Mejia", "GK", 73, "Universitario", 35),
        ("Fidel Escobar", "DEF", 73, "Real Salt Lake", 30),
        ("Andres Andrade_d", "DEF", 0, "", 0),  # placeholder removed below
        ("Eric Davis", "DEF", 73, "Botev Plovdiv", 34),
        ("Michael Murillo", "DEF", 76, "Marseille", 29),
        ("Jose Cordoba", "DEF", 75, "Norwich City", 24),
        ("Cristian Martinez", "DEF", 72, "Sporting San Miguelito", 26),
        ("Roderick Miller", "DEF", 72, "Aris Limassol", 32),
        ("Carlos Harvey", "MID", 73, "Minnesota United", 25),
        ("Cristian Martinez_m", "MID", 73, "Inter Miami", 24),
        ("Edgar Yoel Barcenas", "MID", 73, "Mazatlan", 32),
        ("Anibal Godoy", "MID", 73, "San Jose Earthquakes", 36),
        ("Aaron Zuniga", "FWD", 72, "Atlas", 27),
        ("Cecilio Waterman", "FWD", 73, "Coquimbo Unido", 34),
        ("Tomas Rodriguez", "MID", 71, "Atletico Bucaramanga", 26),
        ("Eduardo Guerrero", "FWD", 72, "Deportivo Saprissa", 30),
        ("Jorge Gutierrez", "MID", 70, "CAI", 25),
        ("Azarias Londono", "FWD", 70, "Plaza Amador", 25),
        ("Adalberto Carrasquilla_d", "MID", 0, "", 0),  # placeholder removed below
        ("Ismael Diaz_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Jiovany Ramos", "DEF", 71, "Plaza Amador", 27),
        ("Jose Luis Rodriguez", "MID", 73, "Gil Vicente", 27),
        ("Gabriel Torres", "FWD", 72, "Universidad de Chile", 37),
        ("Abdiel Ayarza", "FWD", 71, "Cartagines", 33),
    ],
    "Jordan": [
        ("Abdullah Al-Fakhouri", "GK", 71, "Al-Faisaly", 27),
        ("Yousef Abu Jalboush", "GK", 70, "Al-Hussein", 28),
        ("Salem Al-Ajalin", "DEF", 71, "Al-Faisaly", 28),
        ("Bara Marei", "DEF", 71, "Al-Wehdat", 25),
        ("Abdallah Nasib", "DEF", 71, "Al-Ramtha", 28),
        ("Ihsan Haddad", "DEF", 71, "Al-Faisaly", 24),
        ("Mohammad Abu Hasheesh", "DEF", 71, "Al-Wehdat", 28),
        ("Mahmoud Al-Mardi", "DEF", 70, "Al-Hussein", 27),
        ("Noor Al-Rawabdeh_d", "MID", 0, "", 0),  # placeholder removed below
        ("Nizar Al-Rashdan", "MID", 72, "Al-Faisaly", 27),
        ("Ehsan Haddad", "MID", 70, "Al-Wehdat", 25),
        ("Yazan Al-Naimat_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Mahmoud Al-Aqrabawi", "MID", 71, "Al-Hussein", 27),
        ("Ali Olwan", "FWD", 73, "Al-Najma", 27),
        ("Musa Al-Taamari_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Mohammad Abu Zrayq", "MID", 70, "Al-Wehdat", 26),
        ("Yazan Al-Arab_d", "DEF", 0, "", 0),  # placeholder removed below
        ("Hamza Al-Dardour", "FWD", 71, "Sharjah", 34),
        ("Rajaei Ayed", "MID", 70, "Al-Faisaly", 26),
        ("Abdallah Al-Smadi", "DEF", 70, "Al-Hussein", 25),
        ("Mohammad Al-Dmeiri", "FWD", 70, "Al-Wehdat", 23),
        ("Saleh Rateb", "MID", 70, "Al-Faisaly", 23),
        ("Ali Alwan_x", "FWD", 70, "Al-Salt", 24),
        ("Ahmad Samir", "MID", 71, "Al-Hussein", 26),
        ("Bahaa Faisal", "FWD", 70, "Al-Hussein", 24),
        ("Anas Al-Awadat", "FWD", 70, "Al-Faisaly", 28),
    ],
    "Cape Verde": [
        ("Bruno Varela", "GK", 74, "Vitoria Guimaraes", 31),
        ("Marcio Rosa", "GK", 70, "Rio Ave", 28),
        ("Diney Borges", "DEF", 72, "AVS", 28),
        ("Stopira", "DEF", 71, "Fehervar", 37),
        ("Logan Costa", "DEF", 77, "Toulouse", 25),
        ("Roberto Lopes_d", "DEF", 0, "", 0),  # placeholder removed below
        ("Kelvin Pires", "DEF", 71, "Estoril", 24),
        ("Dylan Tavares", "DEF", 71, "Casa Pia", 24),
        ("Sidny Cabral", "DEF", 70, "AVS", 24),
        ("Kenny Rocha_d", "MID", 0, "", 0),  # placeholder removed below
        ("Jamiro Monteiro", "MID", 75, "San Jose Earthquakes", 32),
        ("Deroy Duarte", "MID", 73, "Pyramids", 26),
        ("Laros Duarte", "MID", 72, "Sint-Truiden", 28),
        ("Joao Paulo", "MID", 71, "Casa Pia", 27),
        ("Pico", "MID", 71, "Farense", 27),
        ("Gilson Tavares", "MID", 71, "Estrela Amadora", 25),
        ("Garry Rodrigues_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Ryan Mendes_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Willy Semedo", "FWD", 72, "Casa Pia", 33),
        ("Dailon Livramento", "FWD", 73, "Estrela Amadora", 23),
        ("Bebe", "FWD", 73, "Rayo Vallecano", 35),
        ("Gilberto Comlan", "FWD", 71, "Tondela", 25),
        ("Telmo Arcanjo", "MID", 73, "Tondela", 24),
        ("Patrick Andrade", "MID", 73, "Apollon Limassol", 32),
        ("Gilson Benchimol", "FWD", 72, "Casa Pia", 23),
    ],
    "New Zealand": [
        ("Alex Paulsen", "GK", 73, "Bournemouth", 23),
        ("Oliver Sail", "GK", 70, "Wellington Phoenix", 28),
        ("Tyler Bindon", "DEF", 74, "Nottingham Forest", 20),
        ("Finn Surman", "DEF", 72, "Portland Timbers", 22),
        ("Nando Pijnaker", "DEF", 72, "Rapid Vienna", 27),
        ("Liberato Cacace", "DEF", 75, "Empoli", 25),
        ("Tyler Boyd", "DEF", 71, "Western Sydney Wanderers", 31),
        ("Sam Sutton", "DEF", 70, "Wellington Phoenix", 24),
        ("Joe Bell", "MID", 73, "Viking", 26),
        ("Matthew Garbett", "MID", 73, "Como", 23),
        ("Cameron Howieson", "MID", 71, "Auckland FC", 31),
        ("Clayton Lewis", "MID", 70, "Auckland FC", 28),
        ("Alex Greive", "FWD", 72, "St. Mirren", 26),
        ("Eli Just", "FWD", 71, "Odense", 26),
        ("Kosta Barbarouses", "FWD", 71, "Auckland FC", 36),
        ("Sarpreet Singh", "MID", 73, "Ratchaburi", 27),
        ("Bill Tuiloma", "DEF", 72, "Charlotte FC", 31),
        ("Callum McCowatt", "FWD", 70, "Auckland FC", 27),
        ("Elijah Just", "MID", 70, "Esbjerg", 25),
        ("Storm Roux", "DEF", 70, "Auckland FC", 32),
        ("Ben Old", "FWD", 72, "Saint-Etienne", 23),
    ],
    "Curacao": [
        ("Eloy Room_d", "GK", 0, "", 0),  # placeholder removed below
        ("Kenji Gorre_gk", "GK", 0, "", 0),  # placeholder removed below
        ("Marvin Zeegelaar", "DEF", 73, "Sparta Rotterdam", 35),
        ("Shanon Carmelia", "DEF", 71, "Dordrecht", 26),
        ("Jurien Gaari", "DEF", 71, "Vejle", 30),
        ("Roshon van Eijma", "DEF", 70, "Den Bosch", 26),
        ("Armando Obispo", "DEF", 73, "PSV", 26),
        ("Sherel Floranus", "DEF", 72, "Heerenveen", 27),
        ("Livano Comenencia", "DEF", 72, "Juventus", 21),
        ("Leandro Bacuna_d", "MID", 0, "", 0),  # placeholder removed below
        ("Juninho Bacuna_d", "MID", 0, "", 0),  # placeholder removed below
        ("Kenji Gorre", "MID", 72, "Maccabi Netanya", 31),
        ("Jeremy Antonisse", "MID", 70, "Telstar", 23),
        ("Sontje Hansen", "FWD", 73, "Middlesbrough", 23),
        ("Tahith Chong_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Gervane Kastaneer", "FWD", 71, "Hapoel Beer Sheva", 29),
        ("Kenrich Williams_x", "FWD", 70, "Riga FC", 27),
        ("Ayrton Statie", "FWD", 70, "ADO Den Haag", 25),
        ("Rangelo Janga", "FWD", 72, "CFR Cluj", 33),
        ("Tyrese Noslin", "FWD", 71, "Fortuna Sittard", 23),
        ("Anthony van den Hurk", "FWD", 70, "FCV Dender", 30),
        ("Vurnon Anita", "MID", 71, "Free agent", 36),
        ("Darren Sidoel", "DEF", 70, "Almere City", 28),
        ("Kenneth Vermeer", "GK", 72, "Free agent", 39),
        ("Tyrick Bodak", "GK", 70, "RKC Waalwijk", 25),
        ("Jeremy de Nooijer", "MID", 70, "Den Bosch", 32),
        ("Quenten Martinus", "MID", 71, "Sabah", 30),
    ],
    "Haiti": [
        ("Josue Duverger", "GK", 71, "Le Mans", 27),
        ("Lordy Cherenfant", "GK", 70, "Erzeni", 24),
        ("Ricardo Ade_d", "DEF", 0, "", 0),  # placeholder removed below
        ("Carlens Arcus", "DEF", 72, "Aris Limassol", 29),
        ("Andy Thelusma", "DEF", 71, "Boavista", 24),
        ("Jems Geffrard", "DEF", 71, "Sandefjord", 31),
        ("Christopher Attys", "DEF", 70, "Phoenix Rising", 26),
        ("Garvenson Randolph", "DEF", 70, "Genk", 21),
        ("Danley Jean Jacques_d", "MID", 0, "", 0),  # placeholder removed below
        ("Wilde-Donald Guerrier", "MID", 71, "Sabail", 36),
        ("Carl Sainte", "MID", 70, "Mezokovesd", 27),
        ("Leverton Pierre", "MID", 70, "Phoenix Rising", 25),
        ("Jean Ricner Bellegarde", "MID", 77, "Wolves", 27),
        ("Derrick Etienne", "FWD", 74, "Columbus Crew", 29),
        ("Frantzdy Pierrot_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Duckens Nazon_d", "FWD", 0, "", 0),  # placeholder removed below
        ("Don Deedson Louicius", "FWD", 71, "Hammarby", 23),
        ("Ruben Providence", "FWD", 73, "Goztepe", 24),
        ("Fafa Picault", "FWD", 73, "Houston Dynamo", 34),
        ("Danley Auguste", "MID", 70, "Sigma Olomouc", 24),
        ("Woodgive Predestin", "MID", 70, "Famalicao", 23),
        ("Roberto Lazzarini", "FWD", 70, "Real Hope", 22),
        ("Jean-Kevin Duverne", "DEF", 72, "Lorient", 28),
        ("Bryan Alceus", "MID", 70, "Maccabi Petah Tikva", 26),
        ("Josue Casimir", "FWD", 71, "Beerschot", 23),
    ],
}


def main() -> None:
    data = json.loads(DATA.read_text(encoding="utf-8"))
    by_name = {t["name"]: t for t in data["teams"]}

    for team_name, extra in ADDITIONS.items():
        team = by_name.get(team_name)
        if team is None:
            raise SystemExit(f"unknown team in ADDITIONS: {team_name}")
        existing = {p["name"] for p in team["players"]}
        for name, pos, rating, club, age in extra:
            # Skip the duplicate/placeholder rows (a player already in the base
            # file, kept in the list only as a readability marker).
            if rating == 0 or name.endswith(("_c", "_d", "_dup", "_x", "_m", "_gk")):
                continue
            if name in existing:
                continue
            team["players"].append(
                {"name": name, "pos": pos, "rating": rating, "club": club, "age": age}
            )
            existing.add(name)

    # Validate.
    ok = True
    for t in data["teams"]:
        counts: dict[str, int] = {}
        for p in t["players"]:
            counts[p["pos"]] = counts.get(p["pos"], 0) + 1
        names = [p["name"] for p in t["players"]]
        dupes = {n for n in names if names.count(n) > 1}
        n = len(t["players"])
        flag = ""
        if n != 26:
            flag, ok = "  <-- NOT 26", False
        if dupes:
            flag += f"  DUPES: {dupes}"
            ok = False
        if counts.get("GK", 0) < 2 or counts.get("DEF", 0) < 6 \
                or counts.get("MID", 0) < 5 or counts.get("FWD", 0) < 4:
            flag += "  THIN-POS"
        print(f"{t['name']:<22} {n:>2}  "
              f"GK{counts.get('GK',0)} DEF{counts.get('DEF',0)} "
              f"MID{counts.get('MID',0)} FWD{counts.get('FWD',0)}{flag}")

    if not ok:
        raise SystemExit("\nValidation failed: not every team is a clean 26.")

    DATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")
    print("\nWrote", DATA)


if __name__ == "__main__":
    main()
